### ISSUE TITLE
adding a product to cart from the main page causes an error in the store/cart file in the addProductThunk

### ISSUE THREAD

**Issue by FakeBarenziah** [1904gs-daringdragons/shrek2#133]
fixed on my "userformandroutefixes" branch

**Comment by msicil** [comment]
I can't reproduce the issue

**Comment by FakeBarenziah** [comment]
I still get it on the deployed branch when logged in as a user. Can only add from single product component.

**Comment by msicil** [comment]
Resolved, the heroku database reset didn't take
